// This transform config was generated by Snaplet.
// Snaplet found fields that may contain personally identifiable information (PII)
// and used that to populate this file.
import { copycat, faker } from "@snaplet/copycat";
import type { Transform } from "./structure";
export const config: Transform = () => ({});
